version: '3.8'

networks:
  app-network:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php

  postgresql-db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=task_tl_db
      - POSTGRES_USER=task_tl
      - POSTGRES_PASSWORD=task_tl_password
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    restart: always
    build:
      context: ./src
    command: bash -c 'python manage.py migrate && gunicorn --bind :8000 --workers 3 core.wsgi'
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - postgresql-db
    networks:
      - app-network
