name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  test:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build:

    runs-on: ubuntu-latest
    
    steps:
     - name: Deploy using SSH
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.HOST_MY_SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY_MY_SERVER }}
        port: 22
        script: |
            cd /home/backend-music/
            
            rm src/.env
            git pull origin master
            git status
            
            echo DEBUG=${{ secrets.DEBUG }} >> src/.env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> src/.env
            echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> src/.env
            echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> src/.env
            echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> src/.env
            echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> src/.env
            echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> src/.env
            sudo docker-compose up -d --build
